In [1]:
import numpy as np
import sys
import matplotlib
#import pandas as KungfuPanda ahhahahhahah

I Want to chechk My Versions soo 


In [5]:
print("Numpy Version: ", np.__version__)
print("Matplotlib Version: ", matplotlib.__version__)
print("python VErsion:  ",sys.version)


Numpy Version:  1.26.4
Matplotlib Version:  3.8.3
python VErsion:   3.11.5 (main, Sep 11 2023, 08:31:25) [Clang 14.0.6 ]


In [23]:
inputs=[1,2,3,2.5]

weights=[[0.2,0.8,-0.5,1.0],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]

biases=[2,3,0.5]

"""birDeger=-0.5
weight=0.7
bias=0.7

print(birDeger*weight)
print("----------------------\n")
print(birDeger+bias)
"""


"""
#Neuronla oynamacalar h 🧠
layerOutputs=[]#outputs of current layer mevcut layerın çıktısı
for neuronsWeights,neuronBiases in zip(weights,biases):
    neuronOutput=0#o neuronun çıktısı
    for nInput,weight in zip(inputs,neuronsWeights):
        neuronOutput+=nInput*weight
    neuronOutput=neuronOutput+neuronBiases
    layerOutputs.append(neuronOutput)
print(layerOutputs)
"""





'\n#Neuronla oynamacalar h 🧠\nlayerOutputs=[]#outputs of current layer mevcut layerın çıktısı\nfor neuronsWeights,neuronBiases in zip(weights,biases):\n    neuronOutput=0#o neuronun çıktısı\n    for nInput,weight in zip(inputs,neuronsWeights):\n        neuronOutput+=nInput*weight\n    neuronOutput=neuronOutput+neuronBiases\n    layerOutputs.append(neuronOutput)\nprint(layerOutputs)'

Numpy ile takılmacalar 

In [30]:
import numpy as np
weights=[[0.2,0.8,-0.5,1.0],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]

biases=[2,3,0.5]

bias=2

output=np.dot(weights,inputs)+biases
print(output)

[4.8   1.21  2.385]


Devammm anlıyorum 

In [55]:
import numpy as np
inputs=[[1,2,3,2.5],
        [2.0,5.0,-1.0,2.0],
        [-1.5,2.7,3.3,-0.8]]

weights=[[0.2,0.8,-0.5,1.0],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]

biases=[2,3,0.5]

#ikinicisi geliyor 
weights2=[[0.1,-0.14,0.5],
         [-0.5,0.12,-0.33],
         [-0.44,0.73,-0.13]]

biases2=[-1,2,-0.5]

#matris işlemleri için adjustmentlar 




layer1Output=np.dot(inputs,np.array(weights).T)+biases
#Transpozunu Alıyorum )+biases#.reshape(-1,1) buna ihtiyaç yok şimdilik 
print(layer1Output)
#diğer layer dikkat birinin outputu diğerini inputu 
layer2Output=np.dot(layer1Output,np.array(weights2).T)+biases2
print("\n--------Görmek için-------------\n")
print(layer2Output)


[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]

--------Görmek için-------------

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [86]:
import numpy as np
np.random.seed(0)
X=[[1,2,3,2.5],
   [2.0,5.0,-1.0,2.0],
   [-1.5,2.7,3.3,-0.8]]

class layerDense:
    def __init__(self,nInputs,nNeurons):
        self.weights=0.10*np.random.randn(nInputs,nNeurons)
        self.biases=np.zeros((1,nNeurons))
    def forward(self,inputs):
        self.output=np.dot(inputs,self.weights)+self.biases
    
    
layer1=layerDense(4,5)
layer2=layerDense(5,2)
layer1.forward(X)
print("OUTPUT--> \n",layer1.output)
print("\n----------------\n")

layer2.forward(layer1.output)
print("OUTPUT--> \n",layer2.output)
print("\n----------------\n")

"""
print(layer1.weights)
print("---------------------\n")
print(layer1.biases)
print("---------------------\n")


print("---------------------\n")

print(layer1)

"""


OUTPUT--> 
 [[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]

----------------

OUTPUT--> 
 [[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]

----------------



'\nprint(layer1.weights)\nprint("---------------------\n")\nprint(layer1.biases)\nprint("---------------------\n")\n\n\nprint("---------------------\n")\n\nprint(layer1)\n\n'

In [82]:
import numpy as np
#from layer import Layer

class Dense:
    def __init__(self, input_size, output_size):
        self.weights = 0.10*np.random.randn(output_size, input_size)
        self.bias = np.random.randn(output_size, 1)

    def forward(self, inputs):
        self.output=np.dot(inputs,self.weights,) + self.bias
       
    
layer1=Dense(4,5)
